<style type="text/css">
    #recuperarSenha {
        margin-top: -85px;
        margin-left: 75px;
    }
    #voltarrecuperar {
        margin-top: -85px;
        margin-left: 145px;
    }
    .container {
        width: 450px;
    }
    h2,h3 {
        text-align: center;
    }
</style>
<div class="container">
    <h2>Entrada no sistema</h2>
    <div class="container-fluid">
        <?php echo $this->form; ?>
    </div>
</div>

<div id="modal_recuperar_senha" class="modal closeModal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Recuperação de senha</h3>
    </div>
    <div class="modal-body">
        <?php echo $this->formRecuperar; ?>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/includes/seguranca/login.js"); ?>"></script>