<html lang="pt-br">
    <div class="container">
        <div class="container-fluid">
            <h1>Tipos de conta</h1>
            <div class="pull pull-right">
                <a type="submit" class="btn btn-primary add-tp-conta" href="#">
                    <i class="icon-white icon-plus-sign"></i>
                    Novo
                </a>
                <button type="submit" class="btn btn-danger" id="excluir_conta">
                    <i class="icon-white icon-trash"></i>
                    Excluir
                </button>
            </div>
            <br>
            <hr>
            <?php if ( count($this->conTipoContas) != 0 ) : ?>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Tipo de conta</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                        <?php foreach ( $this->conTipoContas as $tipoContas ) : ?>
                            <?php if ( empty($tipoContas['chv_tp_conta_pai']) ) : ?>
                                <tr class="odd gradeU">
                                    <th>
                                        <input type="checkbox" name="chv_conta" value="<?php echo $tipoContas['chv_tp_conta']; ?>">
                                    </th>
                                    <th>
                                        <?php echo $tipoContas['nom_tipo']; ?>
                                        <br>
                                        <?php foreach ( $this->conTipoContas as $tipoCF ) : ?>
                                            <?php if ( $tipoCF['chv_tp_conta_pai'] == $tipoContas['chv_tp_conta'] ) : ?>
                                                <br>
                                                <a href="#" value="<?php echo $tipoCF['chv_tp_conta']; ?>" class="btEditar" title="Editar"></a>
                                                &nbsp;
                                                <?php echo $tipoCF['nom_tipo']; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </th>
                                    <th>
                                        <a href="#" value="<?php echo $tipoContas['chv_tp_conta']; ?>" class="btEditar" title="Editar"></a>
                                    </th>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else : ?>
                <strong>Não existe contas a vencer</strong>
            <?php endif; ?>
        </div>
    </div>
</html>
<script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/includes/conta/tipoconta.js"); ?>"></script>