<script>
    $(function(){
        $('#informacaoConta-label').addClass('hide');
        $('#dataVencimento-label').addClass('hide');
        $('#dataPagamento-label').addClass('hide');
    });
</script>
<html lang="pt-br">
    <div class="container">
        <div class="container-fluid">
            <h1>Relatório Gerencial das Contas</h1>
            <?php if ( !empty($this->msg) ) : ?>
                <div class="alert alert-block alert-error fade in">
                    <button data-dismiss="alert" class="close" type="button">×</button>
                    <p><?php echo $this->msg; ?></p>
                </div>
            <?php endif; ?>
            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a data-toggle="tab" href="#home">Informação da conta</a></li>
                <li class=""><a data-toggle="tab" href="#vencimento">Vencimento</a></li>
                <li class=""><a data-toggle="tab" href="#pagamento">Pagamento</a></li>
                <?php if ( !empty($this->resultados) ) : ?>
                    <li class=""><a data-toggle="tab" href="#resultado">Resultado da pesquisa</a></li>
                <?php endif; ?>
            </ul>
            <form method="post">
                <div class="pull pull-right">
                    <button type="submit" class="btn btn-primary">
                        <i class="icon-search icon-white"></i>&nbsp;
                        Pesquisa
                    </button>
                    <a href="<?php echo $this->baseUrl('conta/relatorio'); ?>" class="btn"><i class="icon-refresh"></i>&nbsp;Limpar</a>
                </div>
                <div class="tab-content container-fluid" id="myTabContent">
                    <div id="home" class="tab-pane fade active in">
                        <legend>Informações da conta</legend>
                        <?php echo $this->form->getDisplayGroup('informacaoConta'); ?>
                    </div>
                    <div id="vencimento" class="tab-pane fade">
                        <legend>Informações sobre vencimento</legend>
                        <?php echo $this->form->getDisplayGroup('dataVencimento'); ?>
                    </div>
                    <div id="pagamento" class="tab-pane fade">
                        <legend>Informações sobre pagamento</legend>
                        <?php echo $this->form->getDisplayGroup('dataPagamento'); ?>
                    </div>
                    <div id="resultado" class="tab-pane fade">
                        <?php echo $this->render('conta/resultadoRelatorio.phtml'); ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</html>
