<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title> .:SHOME:. </title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="<?php echo $this->baseUrl('/public/css/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl('/public/css/bootstrap-responsive.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl('/public/css/base-admin.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl('/public/css/base-admin-responsive.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl('/public/css/themes.css'); ?>" rel="stylesheet" type="text/css" />

        <!-- Jquery ui-->
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/jquery/jquery-1.9.1.min.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/jquery/jquery-migrate-1.1.1.min.js"); ?>"></script>

        <!-- Bootstrap-->
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/bootstrap/bootstrap.js"); ?>"></script>

        <!-- Jquery ui bootstrap-->
        <link type="text/css" href="<?php echo $this->baseUrl('/public/js/library/jquery-bootstrap/css/custom-theme/jquery-ui-1.10.0.custom.css'); ?>" rel="stylesheet" />
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="<?php echo $this->baseUrl("/public/js/library/html5.js"); ?>"></script>
        <![endif]-->
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/jquery-bootstrap/js/jquery-ui-1.9.2.custom.min.js"); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/jquery-ui/i18n/jquery.ui.datepicker-pt-BR.js"); ?>"></script>

        <!-- ckeditor -->
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/ckeditor/ckeditor.js"); ?>"></script>

        <!-- máscara-->
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/jquery-maskedinput/jquery.maskedinput.js"); ?>"></script>

        <!-- máscara para formato de moeda-->
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/price-format/jquery.price_format.1.7.js"); ?>"></script>

        <!-- Fusion Charts -->
        <script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl("/public/js/library/FusionCharts/JSClass/FusionCharts.js"); ?>"></script>

        <script type="text/javascript">
            var baseUrl = '<?php echo $this->baseUrl(); ?>';
        </script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/script.js"); ?>"></script>
    </head>
j</html>