<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?php echo $this->baseUrl('index'); ?>">Sistema de casa</a>
            <?php if ( !empty($this->objDadosUsuario->chv_usuario) ): ?>
                <div class="nav-collapse collapse">
                    <p class="navbar-text pull-right">
                        <i class="icon-white icon-user"></i>
                        <a href="<?php echo $this->baseUrl('usuario/alterar/id/' . $this->objDadosUsuario->chv_usuario); ?>" class="navbar-link" style="color: #FFF">
                            <?php echo $this->objDadosUsuario->nom_usuario; ?>
                        </a>
                        &nbsp;&nbsp;&nbsp;
                        <a href="<?php echo $this->baseUrl('seguranca/logout'); ?>" title="sair do sistema">
                            <i class="icon-white icon-off"></i>
                        </a>
                    </p>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="dropdown">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="#">Configuração<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl('gerenciamento/email'); ?>">E-mail</a></li>
                                    <li><a href="<?php echo $this->baseUrl('usuario'); ?>">Usuário</a></li>
                                    <li><a href="<?php echo $this->baseUrl('gerenciamento/indexerro'); ?>">Gerenciamento de erros</a></li>
                                    <li><a href="<?php echo $this->baseUrl('gerenciamento/index'); ?>">Gerencimento de armazenamento</a></li>
                                </ul>
                            </li>
                            <ul class="nav">
                                <li class="dropdown">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Entidade<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl('entidade'); ?>">Listagem</a></li>
                                        <li><a href="<?php echo $this->baseUrl('entidade/novo'); ?>">Nova</a></li>
                                        <li><a href="<?php echo $this->baseUrl('entidade/tipoentidade'); ?>">Tipo de entidade</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <ul class="nav">
                                <li class="dropdown">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Contas<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl('conta'); ?>">Listagem</a></li>
                                        <li><a href="<?php echo $this->baseUrl('orcamento'); ?>">Orçamento</a></li>
                                        <li><a href="<?php echo $this->baseUrl('conta/novo'); ?>">Nova</a></li>
                                        <li><a href="<?php echo $this->baseUrl('conta/relatorio'); ?>">Relatório</a></li>
                                        <li><a href="<?php echo $this->baseUrl('relatorio/grafico'); ?>">Relatório com Gráfico</a></li>
                                        <li><a href="<?php echo $this->baseUrl('conta/listagemtipoconta'); ?>">Tipo de conta</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Meus dados<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl('usuario/alterar/id/' . $this->objDadosUsuario->chv_usuario); ?>">Alterar dados</a></li>
                                        <li><a href="#" id="alterar_senha_usuario">Senha</a></li>
                                    </ul>
                                </li>
                            </ul>
                    </div>
                </div><!--/.nav-collapse -->
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="alert-mensagem">
    <?php if ( $this->retorno['mensagem'] != '' ) : ?>
        <div class="alert <?php echo $this->retorno['status']; ?>">
            <strong><?php echo $this->retorno['mensagem']; ?></strong>
        </div>
    <?php endif; ?>
</div>
