<div class="container">
    <div class="row-fluid container-fluid">
        <div class="span4">
            <h2>Supermercado</h2>
            <img width="42" height="54" src="<?php echo $this->baseUrl('/public/img/icon/sacola.png'); ?>">
        </div>
        <div class="span4">
            <h2>Contas</h2>
            <a href="<?php echo $this->baseUrl('conta'); ?>">
                <img width="42" height="54" src="<?php echo $this->baseUrl('/public/img/icon/invoice.png'); ?>">
            </a>
        </div>
    </div>
</div>