<div class="container">
    <h2>Configuração de E-mail</h2>
    <div class="container-fluid">
        <div class="tab-content container-fluid" id="myTabContent">
            <div class="pull-right">
                <a herf="#" id="novaConfig" class="btn btn-primary">
                    <i class="icon-white icon-plus-sign"></i>&nbsp;Adicionar
                </a>
            </div>
            <br><br>
            <div>
                <?php if ( count($this->coEmails) != 0 ) : ?>
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Servidor</th>
                                <th>Usuário</th>
                                <th>E-mail</th>
                                <th>Status</th>
                                <th>Data cadastro</th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ( $this->coEmails as $email ) : ?>
                                <tr>
                                    <th><?php echo $email['servidor']; ?></th>
                                    <th><?php echo $email['nome_usuario']; ?></th>
                                    <th><?php echo $email['usuario']; ?></th>
                                    <th>
                                        <?php if ( $email['status'] ) : ?>
                                            <img id='flag-verde' src="<?php echo $this->baseUrl('/public/img/flag-verde.png'); ?>">
                                        <?php else : ?>
                                            <img id='flag-vermelho' src="<?php echo $this->baseUrl('/public/img/flag-vermelho.png'); ?>">
                                        <?php endif; ?>
                                    </th>
                                    <th>
                                        <?php echo $email['dat_cadastro']; ?>
                                    </th>
                                    <th>
                                        <a href="#" id="editarEmail" value="<?php echo $email['chv_email']; ?>" title="Editar configuração de e-mail">
                                            <i class="icon-pencil"></i>
                                        </a>
                                        <?php if ( $email['status'] ) : ?>
                                            <a href="#" id="status" ref="0" value="<?php echo $email['chv_email']; ?>" title="Inativar a configuração">
                                                <i class="icon-remove-sign"></i>
                                            </a>
                                        <?php else : ?>
                                            <a href="#" id="status" ref="1" value="<?php echo $email['chv_email']; ?>" title="Ativar esta configuração">
                                                <i class="icon-ok"></i>
                                            </a>
                                        <?php endif; ?>
                                    </th>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else : ?>
                    <strong style="background: #ff0000;">Não existem configuração de e-mail cadastrada</strong>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>


<div id="modal_manter_email" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="modalHeader"></h3>
    </div>
    <form id="formManterConfi" action="<?php echo $this->baseUrl('gerenciamento/salvaremail/');?>" method="post">
        <div class="modal-body">
            <input type="hidden" id="chv_email" name="chv_email">
            <div>
                <label>
                    Servidor:
                    <input type="text" class="input-xlarge" id="servidor" required="true" name="servidor" min="5">
                </label>
                <label>
                    Usuário:
                    <input type="text" class="input-xlarge" id="usuario" required="true" name="usuario" min="5">
                </label>
                <strong>Dados de autentificação</strong>
                <label>
                    E-mail:
                    <input type="email" class="input-xlarge" id="email" required="true" name="email" min="5">
                </label>
                <label>
                    Senha:
                    <input type="password" class="input-xlarge" id="senha" required="true" name="senha" min="5">
                </label>
                <span style="color: #ff0000">As configuração serão válidadas pelos dados informados.</span>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            <button type="submit" id="salvar" class="btn btn-success" ><i class="icon-white icon-plus-sign"></i>&nbsp;Salvar</button>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/includes/gerenciamento/email/index.js"); ?>"></script>