<div id="content">

    <div class="container pull form-actions">

        <div class="row">

            <div class="span12">

                <div class="error-container">

                    <h1>Oops!</h1>
                    <div class="error-details">
                        Prezado usuário, ocorreu um e-mail no sistema
                    </div> <!-- /error-details -->

                    <div class="error-actions">
                        <a class="btn btn-large btn-primary" href="<?php echo $this->baseUrl(''); ?>">
                            <i class="icon-white icon-chevron-left"></i>
                            &nbsp;
                            Voltar para o sistema						
                        </a>
                        <a class="btn btn-large" href="./">
                            <i class="icon-envelope"></i>
                            &nbsp;
                            Contatar suporte
                        </a>
                        <div class="container-fluid">
                            <p><?php echo $this->mensagemErro; ?></p>
                        </div>
                    </div> <!-- /error-actions -->

                </div> <!-- /.error-container -->				


            </div> <!-- /.span12 -->

        </div> <!-- /.row -->		

    </div> <!-- /.container -->

</div>