<p>Prezado(a) <strong><?php echo $this->nomeUsuario; ?></strong>,<br />
    <br />
    Segue seus dados de acessos ao sistema.<br />
    <br />
    <strong>Login:</strong> <?php echo $this->loginUsuario; ?><br />
    <strong><span class="il">Senha</span>:</strong> <?php echo $this->senhaUsuario; ?><br />
    <strong><span class="il">Endereço da aplicação</span>:</strong> <?php echo $this->endAPP; ?><br />
    <br />
    Atenciosamente,<br />
    <strong>Administração do SHOME</strong></p>