<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<p>
    Prezado(a) <strong><?php echo $this->nomeUsuario; ?></strong>,
    <br />
    <br />
    Devido a solicita&ccedil;&atilde;o de 
    <span class="il">senha</span> realizada em nosso portal neste instante, enviamos por e-mail seu login e 
    <span class="il">senha</span> para acesso a &aacute;rea restrita do portal.<br />
    <br />
    <strong>Login:</strong> <?php echo $this->loginUsuario; ?><br />
    <strong><span class="il">Senha</span>:</strong> <?php echo $this->senhaUsuario; ?><br />
    <strong><span class="il">Endereço da aplicação</span>:</strong> <?php echo $this->endAPP; ?><br />
    <br />
    Atenciosamente,<br />
    <strong>Administração do SHOME</strong></p>