<script type="text/javascript" src="<?php echo $this->baseUrl("/public/js/includes/relatorio/grafico.js"); ?>"></script>
<div class="container">
    <div class="container-fluid">
        <h1>Relatório das Contas - Gráfico</h1>
        <form action="#" method="post" id="formRelatorioGrafico" class="form-actions">
            <div class="pull pull-right">
                <a href="#" id="pesquisar" class="btn btn-primary"><i class="icon-search icon-white"></i>
                    &nbsp;Pesquisa
                </a>
                <a class="btn" href="/shome/relatorio/grafico"><i class="icon-refresh"></i>&nbsp;Limpar</a>
            </div>
            <div>
                <p>Informe o período para geração do relatório:</p>
                <input type="text" class="input-small data" id="dataInicio" name="dataInicio" required="true" value="01/01/<?php echo date('Y'); ?>">
                &nbsp;à&nbsp;
                <input type="text" class="input-small data" id="dataFim" name="dataFim" required="true" value="31/12/<?php echo date('Y'); ?>">
            </div>
        </form>
        <div id="graficoBarra" class=""></div>
    </div>
</div>